name: Evidence capture for Coauthor
author: Coauthor by Hindsight Software
description: >-
  Uploads test results, reports, and other evidence to Coauthor for ISO/IEC
  62304 and Software as a Medical Device compliance
branding:
  icon: upload-cloud
  color: purple
inputs:
  path:
    description: A file, directory or wildcard pattern that describes what to upload
    required: true
  switem:
    description: The Software Item the evidence is associated with
    required: false
  evidence:
    description: The evidence category
    required: true
  type:
    description: The type of evidence
    required: true
  format:
    description: The format of the evidence
    required: true
  hostname:
    description: The hostname of the server
    default: archive.coauthor.app
    required: false
runs:
  using: node20
  main: dist/index.js
