name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
  switem:
    description: 'The Software Item the evidence is associated with'
    required: false
  evidence:
    description: 'The evidence category'
    required: true
  type:
    description: 'The type of evidence'
    required: true
  format:
    description: 'The format of the evidence'
    required: true
  hostname:
    description: 'The hostname of the server'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
